export const data = [
  {
    title: 'Ruth in the Bardo',
    artist: 'name',
    year: '2023',
    role: 'Producing, Engineering',
    image: 'LFD_FallingInLoveWithYou.jpeg',
    link: 'bandcamp.com/song',
  },
  {
    title: 'Plot Armor',
    artist: "Let's Rally",
    role: 'Engineering, Mixing',
    year: '2022',
    image: 'RP_PlotArmor.jpeg',
    link: 'https://letsrally.bandcamp.com/album/plot-armor ',
  },
  {
    title: "Cryin' with the Homies",
    artist: 'Coach Mike',
    year: '2023',
    role: 'Producing, Engineering, Mixing, Mastering',
    image: 'CM_CryinWithTheHomies.jpeg',
    link: 'https://coachmike.bandcamp.com/track/cryin-with-the-homies',
  },
  {
    title: 'Felt Like Forever EP',
    artist: 'Attic Posture',
    role: 'Producing, Engineering, Mixing, Mastering',
    year: '2022',
    image: 'AP_FeltLikeForever.jpeg',
    link: 'https://atticposture.bandcamp.com/album/felt-like-forever-ep',
  },
  {
    title: 'This Is Our Youth',
    artist: 'Party Harding',
    year: '2023',
    role: 'Engineering, Mixing, Mastering',
    image: 'PH_ThisIsOurYouth.jpeg',
    link: 'https://partyharding.bandcamp.com/album/this-is-our-youth-2',
  },
  {
    title: 'Close Enough EP',
    artist: 'Sweet Jams',
    role: 'Engineering',
    year: '2022',
    image: 'SJ_CloseEnough.jpeg',
    link: 'https://sweetlyjamming.bandcamp.com/album/close-enough-ep',
  },
  {
    title: 'Close My Eyes',
    artist: 'Sweet Jams',
    year: '2023',
    role: 'Engineering',
    image: 'SJ_CloseMyEyes.jpeg',
    link: 'https://sweetlyjamming.bandcamp.com/track/close-my-eyes',
  },
  {
    title: 'Falling In Love With You',
    artist: 'Love For Dinner',
    role: 'Producing, Mixing',
    year: '2022',
    image: 'LFD_FallingInLoveWithYou.jpeg',
    link: 'https://lovefordinner.bandcamp.com/track/falling-in-love-with-you',
  },
];
